server:
  # 设置服务端口
  port: 8080
# spring config
spring:
  # 名称
  application:
    name: demo-todo-list

  # 数据库
  datasource:
    # jdbc 连接方式
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MYSQL url
    url: jdbc:mysql://localhost:3306/spring-boot-crud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    # username
    username: root
    # password
    password: 12345678


  # springdoc-openapi项目配置
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
    api-docs:
      path: /v3/api-docs
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.chuxin.demotodolist.controller

  # knife4j的增强配置，不需要增强可以不配
  knife4j:
    enable: true
    setting:
      language: zh_cn